import type { Metadata, Viewport } from 'next'
import { Space_Grotesk, Plus_Jakarta_Sans, Fira_Code, Cormorant_Garamond } from 'next/font/google'
import './globals.css'

const spaceGrotesk = Space_Grotesk({ subsets: ['latin'], weight: ['400', '500', '600', '700'], display: 'swap', variable: '--font-display' })
const plusJakarta = Plus_Jakarta_Sans({ subsets: ['latin'], weight: ['300', '400', '500', '600', '700', '800'], display: 'swap', variable: '--font-body' })
const firaCode = Fira_Code({ subsets: ['latin'], weight: ['400', '500'], display: 'swap', variable: '--font-mono' })
const cormorant = Cormorant_Garamond({ subsets: ['latin'], weight: ['400', '500', '600'], style: ['italic', 'normal'], display: 'swap', variable: '--font-serif' })



export const metadata: Metadata = {
  metadataBase: new URL('https://digitalcraftstudio.in'),
  title: {
    default: 'Digitalcraft Studio | Digital Growth Agency, SEO & Web Development Vrindavan',
    template: '%s | Digitalcraft Studio',
  },
  description:
    'Top-rated Digital Growth Agency in Vrindavan, UP. Expert in Google Maps Ranking, local SEO, Web Development, Meta Ads, and WhatsApp Automation for local businesses.',
  keywords: [
    'digitalcraft studio',
    'digitalcraftstudio',
    'kanchan digitalcraft vrindavan',
    'digital growth agency vrindavan',
    'website design vrindavan',
    'best website design in vrindavan',
    'affordable website design vrindavan',
    'web development vrindavan',
    'best web development in vrindavan',
    'affordable web development vrindavan',
    'digital marketing vrindavan',
    'best digital marketing in vrindavan',
    'affordable digital marketing vrindavan',
    'SEO services vrindavan',
    'best SEO services in vrindavan',
    'affordable SEO services vrindavan',
    'local SEO vrindavan',
    'best local SEO in vrindavan',
    'affordable local SEO vrindavan',
    'google maps ranking vrindavan',
    'best google maps ranking in vrindavan',
    'affordable google maps ranking vrindavan',
    'facebook ads vrindavan',
    'best facebook ads in vrindavan',
    'affordable facebook ads vrindavan',
    'meta ads vrindavan',
    'best meta ads in vrindavan',
    'affordable meta ads vrindavan',
    'instagram marketing vrindavan',
    'best instagram marketing in vrindavan',
    'affordable instagram marketing vrindavan',
    'whatsapp CRM vrindavan',
    'best whatsapp CRM in vrindavan',
    'affordable whatsapp CRM vrindavan',
    'whatsapp automation vrindavan',
    'best whatsapp automation in vrindavan',
    'affordable whatsapp automation vrindavan',
    'AI automation vrindavan',
    'best AI automation in vrindavan',
    'affordable AI automation vrindavan',
    'lead generation vrindavan',
    'best lead generation in vrindavan',
    'affordable lead generation vrindavan',
    'social media marketing vrindavan',
    'best social media marketing in vrindavan',
    'affordable social media marketing vrindavan',
    'youtube marketing vrindavan',
    'best youtube marketing in vrindavan',
    'affordable youtube marketing vrindavan',
    'branding agency vrindavan',
    'best branding agency in vrindavan',
    'affordable branding agency vrindavan',
    'vrindavan me website banwani hai',
    'website banwani hai vrindavan',
    'vrindavan me online marketing karni hai',
    'online marketing karni hai vrindavan',
    'vrindavan me google par upar aana hai',
    'google par upar aana hai vrindavan',
    'vrindavan me google map me business dalna hai',
    'google map me business dalna hai vrindavan',
    'vrindavan me facebook ads chalana hai',
    'facebook ads chalana hai vrindavan',
    'vrindavan me instagram marketing karni hai',
    'instagram marketing karni hai vrindavan',
    'vrindavan me whatsapp par auto reply',
    'whatsapp par auto reply vrindavan',
    'vrindavan me online leads chahiye',
    'online leads chahiye vrindavan',
    'vrindavan me business badhana hai',
    'business badhana hai vrindavan',
    'vrindavan me hotel ki marketing',
    'hotel ki marketing vrindavan',
    'vrindavan me dharamshala online booking',
    'dharamshala online booking vrindavan',
    'vrindavan me website banwane wala',
    'website banwane wala vrindavan',
    'वेबसाइट डिजाइन vrindavan',
    'वेबसाइट डिजाइन एजेंसी vrindavan',
    'डिजिटल मार्केटिंग vrindavan',
    'डिजिटल मार्केटिंग एजेंसी vrindavan',
    'एसईओ सर्विसेज vrindavan',
    'एसईओ सर्विसेज एजेंसी vrindavan',
    'लोकल एसईओ vrindavan',
    'लोकल एसईओ एजेंसी vrindavan',
    'गूगल मैप्स रैंकिंग vrindavan',
    'गूगल मैप्स रैंकिंग एजेंसी vrindavan',
    'फेसबुक एड्स vrindavan',
    'फेसबुक एड्स एजेंसी vrindavan',
    'इंस्टाग्राम मार्केटिंग vrindavan',
    'इंस्टाग्राम मार्केटिंग एजेंसी vrindavan',
    'व्हाट्सएप ऑटोमेशन vrindavan',
    'व्हाट्सएप ऑटोमेशन एजेंसी vrindavan',
    'लीड जनरेशन vrindavan',
    'लीड जनरेशन एजेंसी vrindavan',
    'डिजिटल मार्केटिंग एजेंसी एजेंसी vrindavan',
    'सस्ती वेबसाइट vrindavan',
    'सस्ती वेबसाइट एजेंसी vrindavan',
    'website design mathura',
    'best website design in mathura',
    'affordable website design mathura',
    'web development mathura',
    'best web development in mathura',
    'affordable web development mathura',
    'digital marketing mathura',
    'best digital marketing in mathura',
    'affordable digital marketing mathura',
    'SEO services mathura',
    'best SEO services in mathura',
    'affordable SEO services mathura',
    'local SEO mathura',
    'best local SEO in mathura',
    'affordable local SEO mathura',
    'google maps ranking mathura',
    'best google maps ranking in mathura',
    'affordable google maps ranking mathura',
    'facebook ads mathura',
    'best facebook ads in mathura',
    'affordable facebook ads mathura',
    'meta ads mathura',
    'best meta ads in mathura',
    'affordable meta ads mathura',
    'instagram marketing mathura',
    'best instagram marketing in mathura',
    'affordable instagram marketing mathura',
    'whatsapp CRM mathura',
    'best whatsapp CRM in mathura',
    'affordable whatsapp CRM mathura',
    'whatsapp automation mathura',
    'best whatsapp automation in mathura',
    'affordable whatsapp automation mathura',
    'AI automation mathura',
    'best AI automation in mathura',
    'affordable AI automation mathura',
    'lead generation mathura',
    'best lead generation in mathura',
    'affordable lead generation mathura',
    'social media marketing mathura',
    'best social media marketing in mathura',
    'affordable social media marketing mathura',
    'youtube marketing mathura',
    'best youtube marketing in mathura',
    'affordable youtube marketing mathura',
    'branding agency mathura',
    'best branding agency in mathura',
    'affordable branding agency mathura',
    'mathura me website banwani hai',
    'website banwani hai mathura',
    'mathura me online marketing karni hai',
    'online marketing karni hai mathura',
    'mathura me google par upar aana hai',
    'google par upar aana hai mathura',
    'mathura me google map me business dalna hai',
    'google map me business dalna hai mathura',
    'mathura me facebook ads chalana hai',
    'facebook ads chalana hai mathura',
    'mathura me instagram marketing karni hai',
    'instagram marketing karni hai mathura',
    'mathura me whatsapp par auto reply',
    'whatsapp par auto reply mathura',
    'mathura me online leads chahiye',
    'online leads chahiye mathura',
    'mathura me business badhana hai',
    'business badhana hai mathura',
    'mathura me hotel ki marketing',
    'hotel ki marketing mathura',
    'mathura me dharamshala online booking',
    'dharamshala online booking mathura',
    'mathura me website banwane wala',
    'website banwane wala mathura',
    'वेबसाइट डिजाइन mathura',
    'वेबसाइट डिजाइन एजेंसी mathura',
    'डिजिटल मार्केटिंग mathura',
    'डिजिटल मार्केटिंग एजेंसी mathura',
    'एसईओ सर्विसेज mathura',
    'एसईओ सर्विसेज एजेंसी mathura',
    'लोकल एसईओ mathura',
    'लोकल एसईओ एजेंसी mathura',
    'गूगल मैप्स रैंकिंग mathura',
    'गूगल मैप्स रैंकिंग एजेंसी mathura',
    'फेसबुक एड्स mathura',
    'फेसबुक एड्स एजेंसी mathura',
    'इंस्टाग्राम मार्केटिंग mathura',
    'इंस्टाग्राम मार्केटिंग एजेंसी mathura',
    'व्हाट्सएप ऑटोमेशन mathura',
    'व्हाट्सएप ऑटोमेशन एजेंसी mathura',
    'लीड जनरेशन mathura',
    'लीड जनरेशन एजेंसी mathura',
    'डिजिटल मार्केटिंग एजेंसी एजेंसी mathura',
    'सस्ती वेबसाइट mathura',
    'सस्ती वेबसाइट एजेंसी mathura',
    'website design agra',
    'best website design in agra',
    'affordable website design agra',
    'web development agra',
    'best web development in agra',
    'affordable web development agra',
    'digital marketing agra',
    'best digital marketing in agra',
    'affordable digital marketing agra',
    'SEO services agra',
    'best SEO services in agra',
    'affordable SEO services agra',
    'local SEO agra',
    'best local SEO in agra',
    'affordable local SEO agra',
    'google maps ranking agra',
    'best google maps ranking in agra',
    'affordable google maps ranking agra',
    'facebook ads agra',
    'best facebook ads in agra',
    'affordable facebook ads agra',
    'meta ads agra',
    'best meta ads in agra',
    'affordable meta ads agra',
    'instagram marketing agra',
    'best instagram marketing in agra',
    'affordable instagram marketing agra',
    'whatsapp CRM agra',
    'best whatsapp CRM in agra',
    'affordable whatsapp CRM agra',
    'whatsapp automation agra',
    'best whatsapp automation in agra',
    'affordable whatsapp automation agra',
    'AI automation agra',
    'best AI automation in agra',
    'affordable AI automation agra',
    'lead generation agra',
    'best lead generation in agra',
    'affordable lead generation agra',
    'social media marketing agra',
    'best social media marketing in agra',
    'affordable social media marketing agra',
    'youtube marketing agra',
    'best youtube marketing in agra',
    'affordable youtube marketing agra',
    'branding agency agra',
    'best branding agency in agra',
    'affordable branding agency agra',
    'agra me website banwani hai',
    'website banwani hai agra',
    'agra me online marketing karni hai',
    'online marketing karni hai agra',
    'agra me google par upar aana hai',
    'google par upar aana hai agra',
    'agra me google map me business dalna hai',
    'google map me business dalna hai agra',
    'agra me facebook ads chalana hai',
    'facebook ads chalana hai agra',
    'agra me instagram marketing karni hai',
    'instagram marketing karni hai agra',
    'agra me whatsapp par auto reply',
    'whatsapp par auto reply agra',
    'agra me online leads chahiye',
    'online leads chahiye agra',
    'agra me business badhana hai',
    'business badhana hai agra',
    'agra me hotel ki marketing',
    'hotel ki marketing agra',
    'agra me dharamshala online booking',
    'dharamshala online booking agra',
    'agra me website banwane wala',
    'website banwane wala agra',
    'वेबसाइट डिजाइन agra',
    'वेबसाइट डिजाइन एजेंसी agra',
    'डिजिटल मार्केटिंग agra',
    'डिजिटल मार्केटिंग एजेंसी agra',
    'एसईओ सर्विसेज agra',
    'एसईओ सर्विसेज एजेंसी agra',
    'लोकल एसईओ agra',
    'लोकल एसईओ एजेंसी agra',
    'गूगल मैप्स रैंकिंग agra',
    'गूगल मैप्स रैंकिंग एजेंसी agra',
    'फेसबुक एड्स agra',
    'फेसबुक एड्स एजेंसी agra',
    'इंस्टाग्राम मार्केटिंग agra',
    'इंस्टाग्राम मार्केटिंग एजेंसी agra',
    'व्हाट्सएप ऑटोमेशन agra',
    'व्हाट्सएप ऑटोमेशन एजेंसी agra',
    'लीड जनरेशन agra',
    'लीड जनरेशन एजेंसी agra',
    'डिजिटल मार्केटिंग एजेंसी एजेंसी agra',
    'सस्ती वेबसाइट agra',
    'सस्ती वेबसाइट एजेंसी agra',
    'website design delhi',
    'best website design in delhi',
    'affordable website design delhi',
    'web development delhi',
    'best web development in delhi',
    'affordable web development delhi',
    'digital marketing delhi',
    'best digital marketing in delhi',
    'affordable digital marketing delhi',
    'SEO services delhi',
    'best SEO services in delhi',
    'affordable SEO services delhi',
    'local SEO delhi',
    'best local SEO in delhi',
    'affordable local SEO delhi',
    'google maps ranking delhi',
    'best google maps ranking in delhi',
    'affordable google maps ranking delhi',
    'facebook ads delhi',
    'best facebook ads in delhi',
    'affordable facebook ads delhi',
    'meta ads delhi',
    'best meta ads in delhi',
    'affordable meta ads delhi',
    'instagram marketing delhi',
    'best instagram marketing in delhi',
    'affordable instagram marketing delhi',
    'whatsapp CRM delhi',
    'best whatsapp CRM in delhi',
    'affordable whatsapp CRM delhi',
    'whatsapp automation delhi',
    'best whatsapp automation in delhi',
    'affordable whatsapp automation delhi',
    'AI automation delhi',
    'best AI automation in delhi',
    'affordable AI automation delhi',
    'lead generation delhi',
    'best lead generation in delhi',
    'affordable lead generation delhi',
    'social media marketing delhi',
    'best social media marketing in delhi',
    'affordable social media marketing delhi',
    'youtube marketing delhi',
    'best youtube marketing in delhi',
    'affordable youtube marketing delhi',
    'branding agency delhi',
    'best branding agency in delhi',
    'affordable branding agency delhi',
    'delhi me website banwani hai',
    'website banwani hai delhi',
    'delhi me online marketing karni hai',
    'online marketing karni hai delhi',
    'delhi me google par upar aana hai',
    'google par upar aana hai delhi',
    'delhi me google map me business dalna hai',
    'google map me business dalna hai delhi',
    'delhi me facebook ads chalana hai',
    'facebook ads chalana hai delhi',
    'delhi me instagram marketing karni hai',
    'instagram marketing karni hai delhi',
    'delhi me whatsapp par auto reply',
    'whatsapp par auto reply delhi',
    'delhi me online leads chahiye',
    'online leads chahiye delhi',
    'delhi me business badhana hai',
    'business badhana hai delhi',
    'delhi me hotel ki marketing',
    'hotel ki marketing delhi',
    'delhi me dharamshala online booking',
    'dharamshala online booking delhi',
    'delhi me website banwane wala',
    'website banwane wala delhi',
    'वेबसाइट डिजाइन delhi',
    'वेबसाइट डिजाइन एजेंसी delhi',
    'डिजिटल मार्केटिंग delhi',
    'डिजिटल मार्केटिंग एजेंसी delhi',
    'एसईओ सर्विसेज delhi',
    'एसईओ सर्विसेज एजेंसी delhi',
    'लोकल एसईओ delhi',
    'लोकल एसईओ एजेंसी delhi',
    'गूगल मैप्स रैंकिंग delhi',
    'गूगल मैप्स रैंकिंग एजेंसी delhi',
    'फेसबुक एड्स delhi',
    'फेसबुक एड्स एजेंसी delhi',
    'इंस्टाग्राम मार्केटिंग delhi',
    'इंस्टाग्राम मार्केटिंग एजेंसी delhi',
    'व्हाट्सएप ऑटोमेशन delhi',
    'व्हाट्सएप ऑटोमेशन एजेंसी delhi',
    'लीड जनरेशन delhi',
    'लीड जनरेशन एजेंसी delhi',
    'डिजिटल मार्केटिंग एजेंसी एजेंसी delhi',
    'सस्ती वेबसाइट delhi',
    'सस्ती वेबसाइट एजेंसी delhi',
    'website design ncr',
    'best website design in ncr',
    'affordable website design ncr',
    'web development ncr',
    'best web development in ncr',
    'affordable web development ncr',
    'digital marketing ncr',
    'best digital marketing in ncr',
    'affordable digital marketing ncr',
    'SEO services ncr',
    'best SEO services in ncr',
    'affordable SEO services ncr',
    'local SEO ncr',
    'best local SEO in ncr',
    'affordable local SEO ncr',
    'google maps ranking ncr',
    'best google maps ranking in ncr',
    'affordable google maps ranking ncr',
    'facebook ads ncr',
    'best facebook ads in ncr',
    'affordable facebook ads ncr',
    'meta ads ncr',
    'best meta ads in ncr',
    'affordable meta ads ncr',
    'instagram marketing ncr',
    'best instagram marketing in ncr',
    'affordable instagram marketing ncr',
    'whatsapp CRM ncr',
    'best whatsapp CRM in ncr',
    'affordable whatsapp CRM ncr',
    'whatsapp automation ncr',
    'best whatsapp automation in ncr',
    'affordable whatsapp automation ncr',
    'AI automation ncr',
    'best AI automation in ncr',
    'affordable AI automation ncr',
    'lead generation ncr',
    'best lead generation in ncr',
    'affordable lead generation ncr',
    'social media marketing ncr',
    'best social media marketing in ncr',
    'affordable social media marketing ncr',
    'youtube marketing ncr',
    'best youtube marketing in ncr',
    'affordable youtube marketing ncr',
    'branding agency ncr',
    'best branding agency in ncr',
    'affordable branding agency ncr',
    'ncr me website banwani hai',
    'website banwani hai ncr',
    'ncr me online marketing karni hai',
    'online marketing karni hai ncr',
    'ncr me google par upar aana hai',
    'google par upar aana hai ncr',
    'ncr me google map me business dalna hai',
    'google map me business dalna hai ncr',
    'ncr me facebook ads chalana hai',
    'facebook ads chalana hai ncr',
    'ncr me instagram marketing karni hai',
    'instagram marketing karni hai ncr',
    'ncr me whatsapp par auto reply',
    'whatsapp par auto reply ncr',
    'ncr me online leads chahiye',
    'online leads chahiye ncr',
    'ncr me business badhana hai',
    'business badhana hai ncr',
    'ncr me hotel ki marketing',
    'hotel ki marketing ncr',
    'ncr me dharamshala online booking',
    'dharamshala online booking ncr',
    'ncr me website banwane wala',
    'website banwane wala ncr',
    'वेबसाइट डिजाइन ncr',
    'वेबसाइट डिजाइन एजेंसी ncr'
  ],
  authors: [{ name: 'Digitalcraft Studio', url: 'https://digitalcraftstudio.in' }],
  creator: 'Digitalcraft Studio',
  publisher: 'Digitalcraft Studio',
  alternates: {
    canonical: 'https://digitalcraftstudio.in',
  },
  openGraph: {
    type: 'website',
    locale: 'en_IN',
    url: 'https://digitalcraftstudio.in',
    siteName: 'Digitalcraft Studio',
    title: 'Digitalcraft Studio - Digital Growth Agency from Vrindavan, India',
    description:
      'Building websites, ranking local businesses on Google Maps, running Meta Ads, and setting up WhatsApp CRM/automations from Vrindavan.',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'Digitalcraft Studio Digital Agency Portfolio',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Digitalcraft Studio - Digital Growth Agency',
    description: 'Web development, Local SEO, Meta Ads & WhatsApp CRM from Vrindavan, India.',
    images: ['/og-image.png'],
    creator: '@digitalcraftstudio',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'ADD_GOOGLE_SEARCH_CONSOLE_CODE_HERE',
  },
  category: 'technology',
  manifest: '/manifest.json',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'Digitalcraft Studio',
  },
}

export const viewport: Viewport = {
  themeColor: '#D4AF37',
}

const localBusinessSchema = {
  '@context': 'https://schema.org',
  '@type': 'LocalBusiness',
  name: 'Digitalcraft Studio',
  alternateName: 'Digitalcraft Studio Digital Agency',
  url: 'https://digitalcraftstudio.in',
  logo: 'https://digitalcraftstudio.in/logo.png',
  image: 'https://digitalcraftstudio.in/og-image.png',
  description:
    'Full Stack Development and Digital Marketing services in Vrindavan, UP. Web development, SEO, Meta Ads, WhatsApp CRM.',
  address: {
    '@type': 'PostalAddress',
    streetAddress: 'Vrindavan',
    addressLocality: 'Vrindavan',
    addressRegion: 'Uttar Pradesh',
    postalCode: '281121',
    addressCountry: 'IN',
  },
  geo: {
    '@type': 'GeoCoordinates',
    latitude: '27.5794',
    longitude: '77.6960',
  },
  telephone: '+91-7906630435',
  email: 'hello@digitalcraftstudio.in',
  priceRange: 'INR 3,000 - INR 1,00,000',
  openingHours: 'Mo-Sa 09:00-20:00',
  areaServed: ['Vrindavan', 'Mathura', 'Agra', 'Delhi NCR', 'India'],
  serviceType: [
    'Web Development',
    'Digital Marketing',
    'SEO Services',
    'Meta Ads Management',
    'WhatsApp CRM',
    'AI Automation',
  ],
  hasMap: 'https://maps.google.com/?q=Vrindavan+UP+India',
}

const websiteSchema = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'Digitalcraft Studio',
  url: 'https://digitalcraftstudio.in',
  potentialAction: {
    '@type': 'SearchAction',
    target: 'https://digitalcraftstudio.in/?s={search_term_string}',
    'query-input': 'required name=search_term_string',
  },
}

const organizationSchema = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'Digitalcraft Studio',
  alternateName: ['Digitalcraft Studio Digital Agency', 'digitalcraftstudio'],
  url: 'https://digitalcraftstudio.in',
  logo: 'https://digitalcraftstudio.in/logoNameMain.webp',
  image: 'https://digitalcraftstudio.in/og-image.png',
  description: 'Digitalcraft Studio is a digital growth agency based in Vrindavan, India. We build websites, rank businesses on Google Maps, run Meta Ads, set up WhatsApp CRM, and build custom AI automation for local businesses in Vrindavan, Mathura, Agra, and Delhi NCR.',
  email: 'hello@digitalcraftstudio.in',
  telephone: '+91-7906630435',
  address: {
    '@type': 'PostalAddress',
    streetAddress: 'Vrindavan',
    addressLocality: 'Vrindavan',
    addressRegion: 'Uttar Pradesh',
    postalCode: '281121',
    addressCountry: 'IN',
  },
  areaServed: [
    { '@type': 'City', name: 'Vrindavan' },
    { '@type': 'City', name: 'Mathura' },
    { '@type': 'City', name: 'Agra' },
    { '@type': 'City', name: 'Delhi' },
    { '@type': 'City', name: 'Noida' },
    { '@type': 'City', name: 'Gurgaon' },
  ],
  founder: {
    '@type': 'Person',
    name: 'Kanchan',
    jobTitle: 'Founder',
  },
  sameAs: [
    'https://facebook.com/',
    'https://instagram.com/',
    'https://linkedin.com/',
    'https://x.com/',
  ],
}

const serviceSchemas = [
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    serviceType: 'Website Development',
    name: 'Website & Landing Pages - Digitalcraft Studio',
    description: 'Mobile-first websites for bookings, enquiries, menus, rooms, tours, coaching, and real estate leads. Starting at INR 8,000.',
    provider: { '@type': 'Organization', name: 'Digitalcraft Studio' },
    areaServed: ['Vrindavan', 'Mathura', 'Agra', 'Delhi NCR'],
    offers: { '@type': 'Offer', price: '8000', priceCurrency: 'INR', priceSpecification: { '@type': 'PriceSpecification', minPrice: '8000', priceCurrency: 'INR' } },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    serviceType: 'Search Engine Optimization',
    name: 'Local SEO & Google Maps - Digitalcraft Studio',
    description: 'Google Business Profile optimization, local keyword ranking, review strategy, and monthly SEO actions for local businesses.',
    provider: { '@type': 'Organization', name: 'Digitalcraft Studio' },
    areaServed: ['Vrindavan', 'Mathura', 'Agra', 'Delhi NCR'],
    offers: { '@type': 'Offer', price: '3000', priceCurrency: 'INR' },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    serviceType: 'Social Media Advertising',
    name: 'Meta Ads & Lead Generation - Digitalcraft Studio',
    description: 'Facebook and Instagram ads designed for calls, WhatsApp chats, bookings, and walk-in enquiries for local businesses.',
    provider: { '@type': 'Organization', name: 'Digitalcraft Studio' },
    areaServed: ['Vrindavan', 'Mathura', 'Agra', 'Delhi NCR'],
    offers: { '@type': 'Offer', price: '5000', priceCurrency: 'INR' },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Service',
    serviceType: 'Business Automation',
    name: 'AI & Business Automation - Digitalcraft Studio',
    description: 'Custom AI automation, CRM systems, WhatsApp auto-replies, lead capture flows, and business dashboards for local businesses.',
    provider: { '@type': 'Organization', name: 'Digitalcraft Studio' },
    areaServed: ['Vrindavan', 'Mathura', 'Agra', 'Delhi NCR', 'India'],
    offers: { '@type': 'Offer', price: '15000', priceCurrency: 'INR' },
  },
]

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'Why does a Vrindavan business need digital marketing?',
      acceptedAnswer: { '@type': 'Answer', text: 'Most customers now search on Google Maps, Instagram, and WhatsApp before they visit, book, or call. A strong digital setup helps hotels, shops, restaurants, tours, and service businesses appear trustworthy and get real enquiries.' },
    },
    {
      '@type': 'Question',
      name: 'Can you help with Google Maps ranking and local SEO?',
      acceptedAnswer: { '@type': 'Answer', text: 'Yes. We work on Google Business Profile optimisation, local keywords, review strategy, service pages, photos, posts, tracking, and website signals so your business has a stronger chance to show for nearby searches.' },
    },
    {
      '@type': 'Question',
      name: 'Do you build websites or only run ads?',
      acceptedAnswer: { '@type': 'Answer', text: 'We do both. We can build fast websites, landing pages, booking pages, WhatsApp lead funnels, Meta ads, Google visibility systems, and monthly reporting depending on what your business needs first.' },
    },
    {
      '@type': 'Question',
      name: 'How soon can I start getting leads?',
      acceptedAnswer: { '@type': 'Answer', text: 'Paid campaigns can start bringing enquiries faster once creatives, targeting, and landing pages are ready. SEO and Google Maps growth usually needs consistent work, but the goal is always practical: more calls, bookings, walk-ins, and WhatsApp chats.' },
    },
    {
      '@type': 'Question',
      name: 'Do you work in Agra and Delhi too?',
      acceptedAnswer: { '@type': 'Answer', text: 'Yes. We work with businesses in Vrindavan, Mathura, Agra, Delhi NCR, and remote locations. The strategy changes by market, but the focus stays the same: calls, bookings, WhatsApp leads, and measurable local visibility.' },
    },
    {
      '@type': 'Question',
      name: 'How does payment work?',
      acceptedAnswer: { '@type': 'Answer', text: 'Most projects start with a confirmed scope and an advance payment. The remaining amount is collected by milestone or before launch, depending on the project size and timeline.' },
    },
    {
      '@type': 'Question',
      name: 'Do you offer monthly packages?',
      acceptedAnswer: { '@type': 'Answer', text: 'Yes. Monthly packages are available for Google Maps SEO, Meta ads, content, reporting, website care, WhatsApp follow-ups, and ongoing growth support.' },
    },
  ],
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusinessSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchemas) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
        />
      </head>
      <body className={`${spaceGrotesk.variable} ${plusJakarta.variable} ${firaCode.variable} ${cormorant.variable} ${plusJakarta.className}`}>

        {children}
      </body>
    </html>
  )
}
